### ISSUE TITLE
데모 페이지가 동작하지 않습니다

### ISSUE THREAD

**Issue by jaeyeonling** [devho813/jajao-talk#6]
동작하게 해주세요 사용해보고 싶어요 엉엉

**Comment by realChanho** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅠㅠ 현재 블랙 해커들의 공격에 의해 서비스 중단 중입니다
더 좋은 서비스로 찾아뵙겠습니다

![image](https://user-images.githubusercontent.com/29947014/126449885-d9ce5090-09a5-4058-a15a-84da87c861b7.png)

**Comment by jaeyeonling** [comment]
좋은 서비스 기대하고 있겠습니다 😄
